Bias correction of numerical prediction model temperature forecast Data Set

https://archive.ics.uci.edu/ml/datasets/Bias+correction+of+numerical+prediction+model+temperature+forecast
Data Set Information:
This data is for the purpose of bias correction of next-day maximum and minimum air temperatures forecast of the LDAPS model operated by the Korea Meteorological Administration over Seoul, South Korea.

This data consists of summer data from 2013 to 2017. The input data is largely composed of the LDAPS model's next-day forecast data, in-situ maximum and minimum temperatures of present-day, and geographic auxiliary variables. There are two outputs (i.e. next-day maximum and minimum air temperatures) in this data. Hindcast validation was conducted for the period from 2015 to 2017.



Attribute Information:
For more information, read [Cho et al, 2020].
1. station - used weather station number: 1 to 25
2. Date - Present day: yyyy-mm-dd ('2013-06-30' to '2017-08-30')
3. Present_Tmax - Maximum air temperature between 0 and 21 h on the present day (Â°C): 20 to 37.6
4. Present_Tmin - Minimum air temperature between 0 and 21 h on the present day (Â°C): 11.3 to 29.9
5. LDAPS_RHmin - LDAPS model forecast of next-day minimum relative humidity (%): 19.8 to 98.5
6. LDAPS_RHmax - LDAPS model forecast of next-day maximum relative humidity (%): 58.9 to 100
7. LDAPS_Tmax_lapse - LDAPS model forecast of next-day maximum air temperature applied lapse rate (Â°C): 17.6 to 38.5
8. LDAPS_Tmin_lapse - LDAPS model forecast of next-day minimum air temperature applied lapse rate (Â°C): 14.3 to 29.6
9. LDAPS_WS - LDAPS model forecast of next-day average wind speed (m/s): 2.9 to 21.9
10. LDAPS_LH - LDAPS model forecast of next-day average latent heat flux (W/m2): -13.6 to 213.4
11. LDAPS_CC1 - LDAPS model forecast of next-day 1st 6-hour split average cloud cover (0-5 h) (%): 0 to 0.97
12. LDAPS_CC2 - LDAPS model forecast of next-day 2nd 6-hour split average cloud cover (6-11 h) (%): 0 to 0.97
13. LDAPS_CC3 - LDAPS model forecast of next-day 3rd 6-hour split average cloud cover (12-17 h) (%): 0 to 0.98
14. LDAPS_CC4 - LDAPS model forecast of next-day 4th 6-hour split average cloud cover (18-23 h) (%): 0 to 0.97
15. LDAPS_PPT1 - LDAPS model forecast of next-day 1st 6-hour split average precipitation (0-5 h) (%): 0 to 23.7
16. LDAPS_PPT2 - LDAPS model forecast of next-day 2nd 6-hour split average precipitation (6-11 h) (%): 0 to 21.6
17. LDAPS_PPT3 - LDAPS model forecast of next-day 3rd 6-hour split average precipitation (12-17 h) (%): 0 to 15.8
18. LDAPS_PPT4 - LDAPS model forecast of next-day 4th 6-hour split average precipitation (18-23 h) (%): 0 to 16.7
19. lat - Latitude (Â°): 37.456 to 37.645
20. lon - Longitude (Â°): 126.826 to 127.135
21. DEM - Elevation (m): 12.4 to 212.3
22. Slope - Slope (Â°): 0.1 to 5.2
23. Solar radiation - Daily incoming solar radiation (wh/m2): 4329.5 to 5992.9
24. Next_Tmax - The next-day maximum air temperature (Â°C): 17.4 to 38.9
25. Next_Tmin - The next-day minimum air temperature (Â°C): 11.3 to 29.8

# Import Libararies

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
pd.set_option('display.max_columns', None)
pd.set_option("max_rows", None)

# Read the Data

In [3]:
df = pd.read_csv('Bias_correction_ucl.csv', parse_dates=['Date'])

In [4]:
df.shape

(7752, 25)

In [19]:
def missing_values_table(df):
        zero_val = (df == 0.00).astype(int).sum(axis=0)
        mis_val = df.isnull().sum()
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        mz_table = pd.concat([zero_val, mis_val, mis_val_percent], axis=1)
        mz_table = mz_table.rename(columns = {0 : 'Zero Values', 1 : 'Missing Values', 2 : '% of Total Missing Values'})
        mz_table['Attributes'] = df.nunique()
        mz_table['Data Type'] = df.dtypes
        
        mz_table = mz_table.sort_values('Attributes', ascending=False).round(1)
        
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns and " + str(df.shape[0]) + " Rows.\n"      
               "There are " + str(mz_table.shape[0]) + " columns that have missing values.")

        return mz_table

missing_values_table(df)

Your selected dataframe has 25 columns and 7588 Rows.
There are 25 columns that have missing values.

,Zero Values,Missing Values,% of Total Missing Values,Attributes,Data Type
LDAPS_LH,0,0,0.0,7588,float64
LDAPS_Tmax_lapse,0,0,0.0,7588,float64
LDAPS_WS,0,0,0.0,7588,float64
LDAPS_Tmin_lapse,0,0,0.0,7588,float64
LDAPS_RHmin,0,0,0.0,7585,float64
LDAPS_RHmax,0,0,0.0,7577,float64
LDAPS_CC3,75,0,0.0,7512,float64
LDAPS_CC2,93,0,0.0,7496,float64
LDAPS_CC1,104,0,0.0,7485,float64
LDAPS_CC4,135,0,0.0,7438,float64
LDAPS_PPT1,4789,0,0.0,2779,float64
LDAPS_PPT2,5094,0,0.0,2479,float64
LDAPS_PPT3,5237,0,0.0,2326,float64
LDAPS_PPT4,5690,0,0.0,1892,float64
Solar radiation,0,0,0.0,1575,float64
Date,0,0,0.0,307,datetime64[ns]
Next_Tmax,0,0,0.0,181,float64
Present_Tmax,0,0,0.0,167,float64
Next_Tmin,0,0,0.0,157,float64
Present_Tmin,0,0,0.0,155,float64
lon,0,0,0.0,25,float64
DEM,0,0,0.0,25,float64
Slope,0,0,0.0,25,float64
station,0,0,0.0,25,float64
lat,0,0,0.0,12,float64

In [6]:
df.dropna(inplace=True)

In [7]:
#lets chcek the null values
df.isnull().sum()

station             0
Date                0
Present_Tmax        0
Present_Tmin        0
LDAPS_RHmin         0
LDAPS_RHmax         0
LDAPS_Tmax_lapse    0
LDAPS_Tmin_lapse    0
LDAPS_WS            0
LDAPS_LH            0
LDAPS_CC1           0
LDAPS_CC2           0
LDAPS_CC3           0
LDAPS_CC4           0
LDAPS_PPT1          0
LDAPS_PPT2          0
LDAPS_PPT3          0
LDAPS_PPT4          0
lat                 0
lon                 0
DEM                 0
Slope               0
Solar radiation     0
Next_Tmax           0
Next_Tmin           0
dtype: int64

In [11]:
df.head()

,station,Date,Present_Tmax,Present_Tmin,LDAPS_RHmin,LDAPS_RHmax,LDAPS_Tmax_lapse,LDAPS_Tmin_lapse,LDAPS_WS,LDAPS_LH,LDAPS_CC1,LDAPS_CC2,LDAPS_CC3,LDAPS_CC4,LDAPS_PPT1,LDAPS_PPT2,LDAPS_PPT3,LDAPS_PPT4,lat,lon,DEM,Slope,Solar radiation,Next_Tmax,Next_Tmin
0,1.0,2013-06-30,28.7,21.4,58.255688,91.116364,28.074101,23.006936,6.818887,69.451805,0.233947,0.203896,0.161697,0.130928,0.0,0.0,0.0,0.0,37.6046,126.991,212.3350,2.7850,5992.895996,29.1,21.2
1,2.0,2013-06-30,31.9,21.6,52.263397,90.604721,29.850689,24.035009,5.691890,51.937448,0.225508,0.251771,0.159444,0.127727,0.0,0.0,0.0,0.0,37.6046,127.032,44.7624,0.5141,5869.312500,30.5,22.5
2,3.0,2013-06-30,31.6,23.3,48.690479,83.973587,30.091292,24.565633,6.138224,20.573050,0.209344,0.257469,0.204091,0.142125,0.0,0.0,0.0,0.0,37.5776,127.058,33.3068,0.2661,5863.555664,31.1,23.9
3,4.0,2013-06-30,32.0,23.4,58.239788,96.483688,29.704629,23.326177,5.650050,65.727144,0.216372,0.226002,0.161157,0.134249,0.0,0.0,0.0,0.0,37.6450,127.022,45.7160,2.5348,5856.964844,31.7,24.3
4,5.0,2013-06-30,31.4,21.9,56.174095,90.155128,29.113934,23.486480,5.735004,107.965535,0.151407,0.249995,0.178892,0.170021,0.0,0.0,0.0,0.0,37.5507,127.135,35.0380,0.5055,5859.552246,31.2,22.5

In [12]:
df.describe()

,station,Present_Tmax,Present_Tmin,LDAPS_RHmin,LDAPS_RHmax,LDAPS_Tmax_lapse,LDAPS_Tmin_lapse,LDAPS_WS,LDAPS_LH,LDAPS_CC1,LDAPS_CC2,LDAPS_CC3,LDAPS_CC4,LDAPS_PPT1,LDAPS_PPT2,LDAPS_PPT3,LDAPS_PPT4,lat,lon,DEM,Slope,Solar radiation,Next_Tmax,Next_Tmin
count,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000,7588.00000,7588.000000,7588.000000,7588.000000,7588.000000,7588.000000
mean,13.014101,29.748366,23.195809,56.724969,88.360823,29.620128,23.511786,7.094097,62.492606,0.368510,0.355528,0.317546,0.298268,0.589008,0.480738,0.275007,0.265373,37.544792,126.99142,61.918136,1.259755,5343.724208,30.241526,22.910820
std,7.217858,2.967401,2.400880,14.626559,7.199456,2.943496,2.342579,2.177034,33.686158,0.262260,0.257922,0.249833,0.253392,1.927577,1.743327,1.146087,1.179661,0.050428,0.07922,54.323529,1.372748,429.782561,3.111807,2.482256
min,1.000000,20.000000,11.300000,19.794666,58.936283,17.624954,14.272646,2.882580,-13.603212,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,37.456200,126.82600,12.370000,0.098500,4329.520508,17.400000,11.300000
25%,7.000000,27.800000,21.600000,45.960243,84.203724,27.673756,22.086820,5.675358,37.206201,0.146546,0.140324,0.100950,0.081495,0.000000,0.000000,0.000000,0.000000,37.510200,126.93700,28.700000,0.271300,5001.485717,28.200000,21.300000
50%,13.000000,29.900000,23.400000,55.023199,89.784122,29.709537,23.758249,6.547838,56.898324,0.315706,0.311676,0.261795,0.227459,0.000000,0.000000,0.000000,0.000000,37.550700,126.99500,45.716000,0.618000,5441.987305,30.400000,23.100000
75%,19.000000,32.000000,24.800000,67.115099,93.742725,31.711109,25.155660,8.028960,84.235666,0.574174,0.557164,0.496444,0.498127,0.052594,0.017735,0.007855,0.000017,37.577600,127.04200,59.832400,1.767800,5729.485840,32.600000,24.600000
max,25.000000,37.600000,29.900000,98.524734,100.000153,38.542255,29.619342,21.857621,213.414006,0.967277,0.968353,0.983789,0.974710,23.701544,21.621661,15.841235,16.655469,37.645000,127.13500,212.335000,5.178200,5992.895996,38.900000,29.800000

# Seprate the Input And Output Model

In [14]:
df.columns

Index(['station', 'Date', 'Present_Tmax', 'Present_Tmin', 'LDAPS_RHmin',
       'LDAPS_RHmax', 'LDAPS_Tmax_lapse', 'LDAPS_Tmin_lapse', 'LDAPS_WS',
       'LDAPS_LH', 'LDAPS_CC1', 'LDAPS_CC2', 'LDAPS_CC3', 'LDAPS_CC4',
       'LDAPS_PPT1', 'LDAPS_PPT2', 'LDAPS_PPT3', 'LDAPS_PPT4', 'lat', 'lon',
       'DEM', 'Slope', 'Solar radiation', 'Next_Tmax', 'Next_Tmin'],
      dtype='object')

In [16]:
#Lets seprate the input and output from train dataset
x=df.drop(columns=['Next_Tmax', 'Next_Tmin','Date'])
y=df[['Next_Tmax']]

In [17]:
x.head()

,station,Present_Tmax,Present_Tmin,LDAPS_RHmin,LDAPS_RHmax,LDAPS_Tmax_lapse,LDAPS_Tmin_lapse,LDAPS_WS,LDAPS_LH,LDAPS_CC1,LDAPS_CC2,LDAPS_CC3,LDAPS_CC4,LDAPS_PPT1,LDAPS_PPT2,LDAPS_PPT3,LDAPS_PPT4,lat,lon,DEM,Slope,Solar radiation
0,1.0,28.7,21.4,58.255688,91.116364,28.074101,23.006936,6.818887,69.451805,0.233947,0.203896,0.161697,0.130928,0.0,0.0,0.0,0.0,37.6046,126.991,212.3350,2.7850,5992.895996
1,2.0,31.9,21.6,52.263397,90.604721,29.850689,24.035009,5.691890,51.937448,0.225508,0.251771,0.159444,0.127727,0.0,0.0,0.0,0.0,37.6046,127.032,44.7624,0.5141,5869.312500
2,3.0,31.6,23.3,48.690479,83.973587,30.091292,24.565633,6.138224,20.573050,0.209344,0.257469,0.204091,0.142125,0.0,0.0,0.0,0.0,37.5776,127.058,33.3068,0.2661,5863.555664
3,4.0,32.0,23.4,58.239788,96.483688,29.704629,23.326177,5.650050,65.727144,0.216372,0.226002,0.161157,0.134249,0.0,0.0,0.0,0.0,37.6450,127.022,45.7160,2.5348,5856.964844
4,5.0,31.4,21.9,56.174095,90.155128,29.113934,23.486480,5.735004,107.965535,0.151407,0.249995,0.178892,0.170021,0.0,0.0,0.0,0.0,37.5507,127.135,35.0380,0.5055,5859.552246

In [18]:
y.head()

   Next_Tmax
0       29.1
1       30.5
2       31.1
3       31.7
4       31.2

# Evaluation

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

def maxr2_score(regr,x,y):
    max_r_score=0
    for r_state in range(42,101):
        X_train, X_test, y_train, y_test = train_test_split(x, y,random_state= r_state,test_size=0.20)
    
        regr.fit(X_train,y_train)

        y_pred = regr.predict(X_test)
        r2_scr=r2_score(y_test,y_pred)
        print("r2_score corresponding to random state:",r_state," is:",r2_scr)
        if r2_scr>max_r_score:
            max_r_score=r2_scr
            final_r_state=r_state
    print()
    print()
    print("max r2 score corresponding to ", final_r_state," is ", max_r_score)
    return final_r_state

# 1.Decision Tree

#Work faster
#Does not require Feature Scaling

In [23]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
r_state = maxr2_score(dt,x,y)

r2_score corresponding to random state: 42  is: 0.7479950904712002
r2_score corresponding to random state: 43  is: 0.7884233414667507
r2_score corresponding to random state: 44  is: 0.7730510089886904
r2_score corresponding to random state: 45  is: 0.7902383728282798
r2_score corresponding to random state: 46  is: 0.7835489294749194
r2_score corresponding to random state: 47  is: 0.7714570548636737
r2_score corresponding to random state: 48  is: 0.765147792147987
r2_score corresponding to random state: 49  is: 0.7817621627408333
r2_score corresponding to random state: 50  is: 0.7827228644171463
r2_score corresponding to random state: 51  is: 0.7656494556675388
r2_score corresponding to random state: 52  is: 0.7806770025498257
r2_score corresponding to random state: 53  is: 0.77417545270478
r2_score corresponding to random state: 54  is: 0.769652970793063
r2_score corresponding to random state: 55  is: 0.7687763159491885
r2_score corresponding to random state: 56  is: 0.7902912872286992
r2_score corresponding to random state: 57  is: 0.7591806254765832
r2_score corresponding to random state: 58  is: 0.7551452291521026
r2_score corresponding to random state: 59  is: 0.7955300342119874
r2_score corresponding to random state: 60  is: 0.7737911256582184
r2_score corresponding to random state: 61  is: 0.793293841758056
r2_score corresponding to random state: 62  is: 0.8007242573704707
r2_score corresponding to random state: 63  is: 0.7750136893675634
r2_score corresponding to random state: 64  is: 0.7741014682376051
r2_score corresponding to random state: 65  is: 0.7767060435628912
r2_score corresponding to random state: 66  is: 0.7665709885571441
r2_score corresponding to random state: 67  is: 0.7708495346412072
r2_score corresponding to random state: 68  is: 0.7757687535109749
r2_score corresponding to random state: 69  is: 0.7793481512189135
r2_score corresponding to random state: 70  is: 0.7849991599800661
r2_score corresponding to random state: 71  is: 0.7886335260208409
r2_score corresponding to random state: 72  is: 0.7632203954710584
r2_score corresponding to random state: 73  is: 0.7599431030279044
r2_score corresponding to random state: 74  is: 0.7696213953124875
r2_score corresponding to random state: 75  is: 0.792320015026446
r2_score corresponding to random state: 76  is: 0.7504419042944157
r2_score corresponding to random state: 77  is: 0.7496907827799639
r2_score corresponding to random state: 78  is: 0.7821335985046032
r2_score corresponding to random state: 79  is: 0.7913674686288374
r2_score corresponding to random state: 80  is: 0.7896146969499318
r2_score corresponding to random state: 81  is: 0.7848028911160569
r2_score corresponding to random state: 82  is: 0.783602116665525
r2_score corresponding to random state: 83  is: 0.768480872014935
r2_score corresponding to random state: 84  is: 0.7827276092527924
r2_score corresponding to random state: 85  is: 0.7808088538548337
r2_score corresponding to random state: 86  is: 0.787820270741684
r2_score corresponding to random state: 87  is: 0.7749119042183226
r2_score corresponding to random state: 88  is: 0.7481263337205775
r2_score corresponding to random state: 89  is: 0.776390158482368
r2_score corresponding to random state: 90  is: 0.7880546179393242
r2_score corresponding to random state: 91  is: 0.7711830252965017
r2_score corresponding to random state: 92  is: 0.7804824849279212
r2_score corresponding to random state: 93  is: 0.7547360028595562
r2_score corresponding to random state: 94  is: 0.7485793630732476
r2_score corresponding to random state: 95  is: 0.7926679705248882
r2_score corresponding to random state: 96  is: 0.7577983600158124
r2_score corresponding to random state: 97  is: 0.7677411881051084
r2_score corresponding to random state: 98  is: 0.7549095707239464
r2_score corresponding to random state: 99  is: 0.7849767225300425
r2_score corresponding to random state: 100  is: 0.7595443470598571


max r2 score corresponding to  62  is  0.8007242573704707

# 2.Random Forest

Random Forest will take Some Time

In [25]:
from sklearn.ensemble import RandomForestRegressor
rtr = RandomForestRegressor()
r_state = maxr2_score(rtr,x,y)

r2_score corresponding to random state: 42  is: 0.8933772441234502
r2_score corresponding to random state: 43  is: 0.9012208694063572
r2_score corresponding to random state: 44  is: 0.8980888579942327
r2_score corresponding to random state: 45  is: 0.9010098474272438
r2_score corresponding to random state: 46  is: 0.8987392116445215
r2_score corresponding to random state: 47  is: 0.8955264366560631
r2_score corresponding to random state: 48  is: 0.9044095074170502
r2_score corresponding to random state: 49  is: 0.8927026801733658
r2_score corresponding to random state: 50  is: 0.903272901407867
r2_score corresponding to random state: 51  is: 0.898247832360606
r2_score corresponding to random state: 52  is: 0.8973852868256222
r2_score corresponding to random state: 53  is: 0.9044656473770106
r2_score corresponding to random state: 54  is: 0.9003026124360232
r2_score corresponding to random state: 55  is: 0.9030022616228772
r2_score corresponding to random state: 56  is: 0.906373535696094
r2_score corresponding to random state: 57  is: 0.8994756176467692
r2_score corresponding to random state: 58  is: 0.9010514714782496
r2_score corresponding to random state: 59  is: 0.9040746236057299
r2_score corresponding to random state: 60  is: 0.9022451460370633
r2_score corresponding to random state: 61  is: 0.9035361319499723
r2_score corresponding to random state: 62  is: 0.9092772715048502
r2_score corresponding to random state: 63  is: 0.903252178812682
r2_score corresponding to random state: 64  is: 0.8835921418232036
r2_score corresponding to random state: 65  is: 0.897747822072949
r2_score corresponding to random state: 66  is: 0.8971437978471634
r2_score corresponding to random state: 67  is: 0.8964477474871392
r2_score corresponding to random state: 68  is: 0.9058607377550699
r2_score corresponding to random state: 69  is: 0.8999874878491461
r2_score corresponding to random state: 70  is: 0.9117066108569377
r2_score corresponding to random state: 71  is: 0.9077074339698739
r2_score corresponding to random state: 72  is: 0.889328613775689
r2_score corresponding to random state: 73  is: 0.9047269548703883
r2_score corresponding to random state: 74  is: 0.8979780532696046
r2_score corresponding to random state: 75  is: 0.9024645024329774
r2_score corresponding to random state: 76  is: 0.8904237928614733
r2_score corresponding to random state: 77  is: 0.8873472341911226
r2_score corresponding to random state: 78  is: 0.900920794193657
r2_score corresponding to random state: 79  is: 0.9067229056198326
r2_score corresponding to random state: 80  is: 0.901952329051726
r2_score corresponding to random state: 81  is: 0.905420708483977
r2_score corresponding to random state: 82  is: 0.9077946348021775
r2_score corresponding to random state: 83  is: 0.9016717930772783
r2_score corresponding to random state: 84  is: 0.9074302749560013
r2_score corresponding to random state: 85  is: 0.9134340492197965
r2_score corresponding to random state: 86  is: 0.9030184516265164
r2_score corresponding to random state: 87  is: 0.8960139402319213
r2_score corresponding to random state: 88  is: 0.8909359096790208
r2_score corresponding to random state: 89  is: 0.907384972339987
r2_score corresponding to random state: 90  is: 0.90289890419557
r2_score corresponding to random state: 91  is: 0.8862159385196519
r2_score corresponding to random state: 92  is: 0.907996007703342
r2_score corresponding to random state: 93  is: 0.9019533211975359
r2_score corresponding to random state: 94  is: 0.8981174159958687
r2_score corresponding to random state: 95  is: 0.9038669191016091
r2_score corresponding to random state: 96  is: 0.8998376158322153
r2_score corresponding to random state: 97  is: 0.8998919901350428
r2_score corresponding to random state: 98  is: 0.9024581660912355
r2_score corresponding to random state: 99  is: 0.9056640930050809
r2_score corresponding to random state: 100  is: 0.8986231207594709


max r2 score corresponding to  85  is  0.9134340492197965

# Cross Validation

In [32]:
#lets do the cross validation
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestRegressor(),x,y,cv=5,scoring="r2")
#the below cross validation score is less and it shows that we further need to improve our model using more data

array([0.71344645, 0.64375808, 0.64237698, 0.79507251, 0.660223  ])

# Final Model

# Prediction

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state = 85,test_size=0.20)
rtr.fit(x_train,y_train)
y_pred=rtr.predict(x_test)

In [35]:
print("RMSE is: ",np.sqrt(mean_squared_error(y_test,y_pred)))
print("r2_score is: ",r2_score(y_test,y_pred))

RMSE is:  0.9215110006799574
r2_score is:  0.9126963717697991

# Storing The Prediction

In [36]:
#lets make the dataframe for price_pred
y_pred_TMax=pd.DataFrame(y_pred,columns=["Next_TMax_Prediction"])

# For Next_TMin

In [38]:
y=df[['Next_Tmin']]

In [39]:
from sklearn.ensemble import RandomForestRegressor
rtr = RandomForestRegressor()
r_state = maxr2_score(rtr,x,y)

r2_score corresponding to random state: 42  is: 0.8993053939302997
r2_score corresponding to random state: 43  is: 0.9106459896549521
r2_score corresponding to random state: 44  is: 0.9017773902171562
r2_score corresponding to random state: 45  is: 0.9073095802718422
r2_score corresponding to random state: 46  is: 0.9003349040689923
r2_score corresponding to random state: 47  is: 0.8976513232883545
r2_score corresponding to random state: 48  is: 0.9109266287446218
r2_score corresponding to random state: 49  is: 0.9064337218306278
r2_score corresponding to random state: 50  is: 0.9060283361619373
r2_score corresponding to random state: 51  is: 0.9117141575294306
r2_score corresponding to random state: 52  is: 0.9051466636231176
r2_score corresponding to random state: 53  is: 0.9072482959015957
r2_score corresponding to random state: 54  is: 0.9081681119583219
r2_score corresponding to random state: 55  is: 0.9046783310786026
r2_score corresponding to random state: 56  is: 0.9104469536672154
r2_score corresponding to random state: 57  is: 0.8976009583934124
r2_score corresponding to random state: 58  is: 0.9083202915352214
r2_score corresponding to random state: 59  is: 0.8993126620306292
r2_score corresponding to random state: 60  is: 0.9163681414665259
r2_score corresponding to random state: 61  is: 0.9071154715058619
r2_score corresponding to random state: 62  is: 0.9129231607829413
r2_score corresponding to random state: 63  is: 0.9012549192243501
r2_score corresponding to random state: 64  is: 0.9131695488616837
r2_score corresponding to random state: 65  is: 0.9028866481484107
r2_score corresponding to random state: 66  is: 0.9038079518532078
r2_score corresponding to random state: 67  is: 0.9004651234312957
r2_score corresponding to random state: 68  is: 0.9187842789385119
r2_score corresponding to random state: 69  is: 0.8927361395951022
r2_score corresponding to random state: 70  is: 0.9179964290731591
r2_score corresponding to random state: 71  is: 0.9116218844913035
r2_score corresponding to random state: 72  is: 0.9030482928041733
r2_score corresponding to random state: 73  is: 0.897783693110919
r2_score corresponding to random state: 74  is: 0.9043618891921315
r2_score corresponding to random state: 75  is: 0.9110113762813363
r2_score corresponding to random state: 76  is: 0.9021338987534765
r2_score corresponding to random state: 77  is: 0.9004002652154746
r2_score corresponding to random state: 78  is: 0.9068700428340064
r2_score corresponding to random state: 79  is: 0.9041009232593973
r2_score corresponding to random state: 80  is: 0.9001164960187683
r2_score corresponding to random state: 81  is: 0.9125817512939507
r2_score corresponding to random state: 82  is: 0.901456695166144
r2_score corresponding to random state: 83  is: 0.9073432158293329
r2_score corresponding to random state: 84  is: 0.9087661569685811
r2_score corresponding to random state: 85  is: 0.9160131788988862
r2_score corresponding to random state: 86  is: 0.905343692805433
r2_score corresponding to random state: 87  is: 0.906002428446005
r2_score corresponding to random state: 88  is: 0.9056896583983199
r2_score corresponding to random state: 89  is: 0.9012627621267782
r2_score corresponding to random state: 90  is: 0.9169274651239798
r2_score corresponding to random state: 91  is: 0.9101729593397708
r2_score corresponding to random state: 92  is: 0.9056883668763486
r2_score corresponding to random state: 93  is: 0.9012254730706906
r2_score corresponding to random state: 94  is: 0.9075356494583607
r2_score corresponding to random state: 95  is: 0.9060816717111421
r2_score corresponding to random state: 96  is: 0.9014236069095584
r2_score corresponding to random state: 97  is: 0.9032703930246372
r2_score corresponding to random state: 98  is: 0.903423494647505
r2_score corresponding to random state: 99  is: 0.9096778952484631
r2_score corresponding to random state: 100  is: 0.9074403614386242


max r2 score corresponding to  68  is  0.9187842789385119

# Cross Validation

In [40]:
#lets do the cross validation
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestRegressor(),x,y,cv=5,scoring="r2")
#the below cross validation score is less and it shows that we further need to improve our model using more data

array([0.68144191, 0.67694875, 0.81378551, 0.86886775, 0.87730738])

# Final Model

# Prediction

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state = 85,test_size=0.20)
rtr.fit(x_train,y_train)
y_pred=rtr.predict(x_test)

In [42]:
print("RMSE is: ",np.sqrt(mean_squared_error(y_test,y_pred)))
print("r2_score is: ",r2_score(y_test,y_pred))

RMSE is:  0.7318177888115867
r2_score is:  0.916274586026408

# Storing The Prediction

In [43]:
#lets make the dataframe for price_pred
y_pred_TMin=pd.DataFrame(y_pred,columns=["Next_TMin_Prediction"])

# Saving The File

In [ ]:
#Storing results as csv
y_pred_TMax.to_csv("Next_TMax_Prediction.csv",index=False)

In [ ]:
y_pred_TMin.to_csv("Next_TMin_Prediction.csv",index=False)